---
- name: Add Vector APT repository
  become: true
  ansible.builtin.shell: |
    bash -c "$(curl -L https://setup.vector.dev)"
  args:
    creates: /etc/apt/sources.list.d/vector.list

- name: Install Vector via APT
  become: true
  ansible.builtin.apt:
    name: vector
    state: present
    update_cache: yes

- name: Ensure directory for vector config exists
  ansible.builtin.file:
    path: "{{ vector_config_path | dirname }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Template config vector
  ansible.builtin.template:
    src: templates/vector.toml.j2
    dest: "{{ vector_config_path }}"
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Start vector service
