---
driver:
  name: podman
platforms:
  - name: oraclelinux
    image: oraclelinux:8
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
