---
- name: Verify Vector role
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Check if vector binary is installed
      ansible.builtin.command: vector --version
      register: vector_version
      changed_when: false
      failed_when: vector_version.rc != 0

    - name: Check vector config validity
      ansible.builtin.command: vector validate --skip-healthchecks /etc/vector/vector.toml
      register: config_check
      changed_when: false
      failed_when: config_check.rc != 0