---
driver:
  name: docker
lint: |
  yamllint .
platforms:
  - name: ubuntu22
    image: ubuntu-python:22.04
    pre_build_image: true
  - name: oraclelinux
    image: oraclelinux:8
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
